# docker-compose.yml
# web interface running locally on http://localhost:8081
version: '3.8'

services:
  mongo:
    image: 'mongo:latest'
    ports:
      - 27017:27017
    volumes:
      - my-data:/var/lib/mongodb/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password!

  mongo-express:
    image: 'mongo-express:latest'
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password!
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo

volumes:
  my-data: